server:
  port: 8092
  # Kafka Configuration
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:PLAINTEXT://kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://schema-registry:8081
  # Enable scheduling
  task:
    scheduling.pool.size: 5
  # Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
    health:
      show-details: always
  # OpenTelemetry Configuration
otel:
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://alloy:4317}
  metric:
    export:
      interval: 60000