server.port=8085

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Enable scheduling
spring.task.scheduling.pool.size=5

# Actuator configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# OpenTelemetry Configuration
otel.exporter.otlp.endpoint=http://localhost:4317
otel.metric.export.interval=60000