springBootVersion=3.5.0
springDependencyManagementVersion=1.1.4
appVersion=1.0.0
javaLanguageVersion=24


springKafkaVersion=3.3.6
kafkaAvroSerializerVersion=7.5.0
avroVersion=1.11.3
confluentSchemaRegistryClientVersion=7.5.0

micrometerVersion=1.14.0
micrometerRegistryPrometheusVersion=1.14.0
opentelemetrySpringBootVersion=2.6.0
opentelemetryExporterOtlp=1.49.0

logstashEncoderVersion=7.4
lombokVersion=1.18.42

testcontainersVersion=1.20.4
junitJupiterVersion=5.11.3

avroPluginVersion=1.9.1

shardingsphereVersion=5.4.1